apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: stories-pvc
spec:
  volumeName: stories-pv
  storageClassName: hostpath
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1G"