apiVersion: v1
kind: PersistentVolume
metadata:
  name: tasks-host-pv
spec: 
  storageClassName: hostpath
  capacity:
    storage: "250m"
  volumeMode: Filesystem
  accessModes:
    - "ReadWriteOnce"
  hostPath: 
    path: /data
    type: DirectoryOrCreate