apiVersion: v1
kind: PersistentVolume
metadata:
  name: tasks-host-pv
spec: 
  capacity:
    storage: "250m"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnly
  hostPath: 
    path: /data
    type: DirectoryOrCreate