## AUTH API HTTP REQUEST 
@host_name = multi-apps.io
@port = 8002
@protocol = http
# @host = {{protocol}}://{{host_name}}:{{port}}
@host = {{protocol}}://{{host_name}}/auth
@contentType = "application/json;charset=utf8"

### Get Default Test Path
GET {{host}}/ HTTP/1.1

### Verify Password Token
GET {{host}}/verify-token/abc HTTP/1.1

### Test Passwork Hashing
GET {{host}}/token/sected-app/secret-pass HTTP/1.1

### Fake check hashed password
GET {{host}}/hashed-password/secret-pass HTTP/1.1