services:
  k8s-vol:
    build: 
      context: .
    container_name: k8s-data-test
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - stories:/app/story
      - /app/node_modules

volumes:
  stories: