apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-app
spec:
  selector:
    matchLabels:
      app: k8s-app
  template:
    metadata:
      labels:
        app: k8s-app
    spec:
      containers:
      - name: k8s-app
        image: marknjo/kub-test-app:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-app
spec:
  selector:
    app: k8s-app
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080

