apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-app-dpy

spec:
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: test-app
        image: marknjo/kub-test-app:latest
        # imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-app-srv
spec:
  selector:
    app: test-app
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
