apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kub-test-srv
  labels:
    name: test-srv
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1

spec:
  ingressClassName: nginx
  rules:
  - host: kubtest.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: k8s-app-srv
            port: 
              number: 8080
