services:
  users:
    build: 
      context: .
    container_name: users-api-cnt
    ports:
      - 8002:8002
    environment:
      - PORT=8002
      - HOST=localhost
      - PROTOCOL=http
    volumes:
      - ./:/app
      - /app/node_modules